name: Pull Request Workflow

on:
 pull_request:
  types:
   - opened
   - synchronize
   - closed
   - reopened

jobs:
 process-pull-request:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Install dependencies
     run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

   - name: Build and test
     run: 
      python script.py  # Adjust this line based on your build process 
